### ISSUE TITLE
Remaining tasks

### ISSUE THREAD

**Issue by kof** [iamstarkov/theming#1]
- [x] Documentation
- [x] Example
- [x] Playground
- [x]  Add tests for withTheme

Main issue https://github.com/cssinjs/jss/issues/488

**Comment by iamstarkov** [comment]
* **Add tests for withTheme** is finished

**Comment by iamstarkov** [comment]
fyi, tests are finished

**Comment by iamstarkov** [comment]
Playground is the only thing which left. Though, i couldnt get online tools like https://www.webpackbin.com/ or https://codesandbox.io/ to work for me. Both of it couldnt handle node_modules.

**Comment by iamstarkov** [comment]
can anybody try as well?

**Comment by Gertt** [comment]
Not sure about what you are trying to achieve with regards to a playground. Simply building an example with webpackbin worked for me though: https://www.webpackbin.com/bins/-KlVZN9q82l11_bxHdjQ

If there is anything I can help with, please let me know. I'm eagerly awaiting the release of this package.

**Comment by iamstarkov** [comment]
@Gertt, its good. can you add PureComponent to demo that it works through it?

**Comment by Gertt** [comment]
Something like this?

https://www.webpackbin.com/bins/-KlVZN9q82l11_bxHdjQ

**Comment by iamstarkov** [comment]
@Gertt that would be nice

**Comment by Gertt** [comment]
Not a designer obviously, but this does give a more visual representation:

https://www.webpackbin.com/bins/-KlsWD4r_aPN8w42LvoT

**Comment by iamstarkov** [comment]
@Gertt its good

**Comment by iamstarkov** [comment]
@Gertt i made few improvements https://www.webpackbin.com/bins/-Km8TglfWP84oYhDquT1

do you like it?

**Comment by Gertt** [comment]
Looks good to me! Excited to see things moving along

**Comment by iamstarkov** [comment]
![theming](https://user-images.githubusercontent.com/559321/26953553-5049761e-4cab-11e7-848f-9056684487cd.gif)
