### ISSUE TITLE
Opt out of error if there is no theme context in the tree

### ISSUE THREAD

**Issue by kentcdodds** [iamstarkov/theming#13]
[This is what we do in glamorous](https://github.com/paypal/glamorous/blob/0bfda9fa8e33453b9b71e95ea5683634d1900184/src/with-theme.js#L26-L32)

```javascript
function generateWarningMessage(Comp) {
  const componentName = Comp.displayName || Comp.name || 'FunctionComponent'
  // eslint-disable-next-line max-len
  return `glamorous warning: Expected component called "${componentName}" which uses withTheme to be within a ThemeProvider but none was found.`
}
// ...

// ...
    componentWillMount() {
      if (!this.context[CHANNEL]) {
        if (process.env.NODE_ENV !== 'production' && !this.warned) {
          this.warned = true
          // eslint-disable-next-line no-console
          console.warn(generateWarningMessage(ComponentToTheme))
        }
      }
// ...
```

I'd also love it if this could be disabled. For `GlamorousComponents`, they all need to be themeable, but not always will they be inside a ThemeProvider (you can pass the theme/override via props). So in `glamorous` we also accept options: `withTheme(Comp, {noWarn: true})`.

**Comment by iamstarkov** [comment]
right now `withTheme` will throw error if its used without `ThemeProvider` https://github.com/iamstarkov/theming/blob/master/src/create-with-theme.js#L22

**Comment by kentcdodds** [comment]
Ah, in that case, I'd like a way to opt out of that :)

**Comment by iamstarkov** [comment]
you might want to take a look at themeListener in #3, because it's exactly about that level of deep integration.

**Comment by iamstarkov** [comment]
pls take a look into that, there is also published theming package in my npm scope with that pr published

**Comment by kentcdodds** [comment]
That looks like it'll work :+1: Thanks!
