### ISSUE TITLE
UMD bundle

### ISSUE THREAD

**Issue by vesparny** [iamstarkov/theming#9]
I see there is no UMD bundle at the moment (https://unpkg.com/theming@1.0.1/dist/)

Would it make sense to have one? I think without it people not using a bundler won't be able to use theming (mainly because dependencies are not bundled in `cjs/es` dist files)

@kentcdodds what do you think? I'm a little bit lost when I have to deal with dist files :)

**Comment by iamstarkov** [comment]
its not a big deal to have one.

At the same time as far as this lib is going to be used tightly with react and cssinjs libs, i'm struggling to come up with any possible use case for umd bundle

**Comment by kentcdodds** [comment]
> its not a big deal to have one

Agreed. I only added one to my libs so people could play with them in the browser via tools like codepen and jsbin. But now that we have codesandbox and webpackbin I see UMD builds as less necessary.

It's definitely a nice to have, but not really a must.

**Comment by kentcdodds** [comment]
If you _do_ want to have one, then you'll mark `peerDependencies` (like React) as `externals` and you'll bundle all other dependencies with the UMD bundle. That's what we do for `glamorous` (we have React and glamor as externals and reference the global variables from their UMD bundles instead).

**Comment by Gertt** [comment]
You could use the relevant parts from [this PR](https://github.com/iamstarkov/theming/pull/6) if you want to add UMD bundle, but I agree that it's not a must.

**Comment by iamstarkov** [comment]
@Gertt yep, your pull-request will be used as reference =)

**Comment by iamstarkov** [comment]
lets close it for now, as far as we have webpackbin and codesandbox to use for react demos

**Comment by iamstarkov** [comment]
everyone, who came into this issue in search for umd bundle: if you need one and you are not happy with webpackbin or codesandbox please to share yours use cases and we will help
